# Form implementation generated from reading ui file '.\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from new_note import Ui_Dialog

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.createNoteButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.createNoteButton.setGeometry(QtCore.QRect(10, 10, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.createNoteButton.setFont(font)
        self.createNoteButton.setDefault(False)
        self.createNoteButton.setFlat(False)
        self.createNoteButton.setObjectName("createNoteButton")
        self.notesLayoutLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.notesLayoutLabel.setGeometry(QtCore.QRect(10, 50, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.notesLayoutLabel.setFont(font)
        self.notesLayoutLabel.setWordWrap(False)
        self.notesLayoutLabel.setObjectName("notesLayoutLabel")
        self.openNoteButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.openNoteButton.setGeometry(QtCore.QRect(640, 540, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.openNoteButton.setFont(font)
        self.openNoteButton.setDefault(False)
        self.openNoteButton.setFlat(False)
        self.openNoteButton.setObjectName("openNoteButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 80, 771, 451))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.actionCreate_new_note = QtGui.QAction(parent=MainWindow)
        self.actionCreate_new_note.setObjectName("actionCreate_new_note")
        self.actionOpen_note = QtGui.QAction(parent=MainWindow)
        self.actionOpen_note.setObjectName("actionOpen_note")

        self.createNoteButton.clicked.connect(self.openNoteCreator)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.createNoteButton.setText(_translate("MainWindow", "Create new note"))
        self.notesLayoutLabel.setText(_translate("MainWindow", "Recently edited notes:"))
        self.openNoteButton.setText(_translate("MainWindow", "Open note"))
        self.actionCreate_new_note.setText(_translate("MainWindow", "Create new note"))
        self.actionOpen_note.setText(_translate("MainWindow", "Open note"))

    def openNoteCreator(self):
        Dialog = QtWidgets.QDialog()
        ui = Ui_Dialog()
        ui.setupUi(Dialog)
        Dialog.exec()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
