# Form implementation generated from reading ui file '.\NewNoteDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt6 import QtCore, QtGui, QtWidgets

class FilePathTextEdit(QtWidgets.QTextEdit):
    def mouseDoubleClickEvent(self, e: QtGui.QMouseEvent) -> None:
        fileManager = QtWidgets.QFileDialog(self)
        folderPath = fileManager.getExistingDirectory()

        if folderPath:
            self.setText(folderPath)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 164)
        self.newNoteLabel = QtWidgets.QLabel(parent=Dialog)
        self.newNoteLabel.setGeometry(QtCore.QRect(10, 70, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.newNoteLabel.setFont(font)
        self.newNoteLabel.setObjectName("newNoteLabel")
        self.newNoteNameTextEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.newNoteNameTextEdit.setGeometry(QtCore.QRect(10, 90, 381, 31))
        self.newNoteNameTextEdit.setObjectName("newNoteNameTextEdit")
        self.saveNoteButton = QtWidgets.QPushButton(parent=Dialog)
        self.saveNoteButton.setGeometry(QtCore.QRect(284, 130, 111, 24))
        self.saveNoteButton.setObjectName("saveNoteButton")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 361, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.newNotePathTextEdit = FilePathTextEdit(parent=Dialog)
        self.newNotePathTextEdit.setGeometry(QtCore.QRect(10, 30, 381, 31))
        self.newNotePathTextEdit.setObjectName("newNotePathTextEdit")

        self.dialog = Dialog
        self.saveNoteButton.clicked.connect(self.createNewNote)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Note creator"))
        self.newNoteLabel.setText(_translate("Dialog", "Enter new note name:"))
        self.saveNoteButton.setText(_translate("Dialog", "Save note"))
        self.label.setText(_translate("Dialog", "Choose destination folder (double click to open file manager):"))

    def createNewNote(self):
        folderPath = self.newNotePathTextEdit.toPlainText()
        filename = self.newNoteNameTextEdit.toPlainText()

        if folderPath and filename:
            filePath = os.path.join(folderPath, f"{filename}.txt")
            with open(filePath, 'w') as file:
                file.write('')
            QtWidgets.QMessageBox.information(None, "Success", "Note saved successfully!")
            self.dialog.close()
        elif filename:
            QtWidgets.QMessageBox.information(None, "Fialure", "Missing destination folder!")
        elif folderPath:
            QtWidgets.QMessageBox.information(None, "Failure", "Missing file name!")
        else:
            QtWidgets.QMessageBox.information(None, "Failure", "Missing both information!")

        
            

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())