# Form implementation generated from reading ui file '.\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import os, sys
from PyQt6.QtWidgets import QApplication, QMainWindow, QWidget, QTableView, QMenuBar, QMenu, QGridLayout, QHBoxLayout, QPushButton, QLabel
from PyQt6.QtCore import QRect
from PyQt6.QtGui import QAction, QIcon,  QFont
from database_modules import Users, Notes

class UserNotesWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.iconPath = os.path.join(os.getcwd(),"Icons")

        self.setWindowTitle(f"Notes")
        self.resize(800, 600)

        self.centralNoteWidget = QWidget()
        self.centralNoteWidget.setObjectName("centralNoteWidget")
        self.setCentralWidget(self.centralNoteWidget)

        self.mainLayout = QGridLayout(self.centralNoteWidget)

        self.createNoteButton = QPushButton(self.centralNoteWidget)
        self.createNoteButton.setGeometry(QRect(10, 10, 141, 31))
        self.createNoteButton.setObjectName("createNoteButton")
        self.createNoteButton.setText("Create new note")
    
        self.notesLayoutLabel = QLabel(self.centralNoteWidget)
        self.notesLayoutLabel.setGeometry(QRect(10, 50, 51, 16))
        self.notesLayoutLabel.setObjectName("notesLayoutLabel")
        self.notesLayoutLabel.setText("Notes: ")

        self.tableView = QTableView(self.centralNoteWidget)
        self.tableView.setGeometry(QRect(10, 70, 781, 461))
        self.tableView.setObjectName("tableView")

        self.openNoteButton = QPushButton(self.centralNoteWidget)
        self.openNoteButton.setGeometry(QRect(640, 540, 141, 31))
        self.openNoteButton.setObjectName("openNoteButton")
        self.openNoteButton.setText("Edit note")

        self.deleteButton = QPushButton(self.centralNoteWidget)
        self.deleteButton.setGeometry(QRect(490, 540, 141, 31))
        self.deleteButton.setObjectName("deleteButton")
        self.deleteButton.setText("Delete")

        self.menubar = QMenuBar()
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")

        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuFile.setTitle("File")

        self.menuAccount = QMenu(self.menubar)
        self.menuAccount.setObjectName("menuAccount")
        self.menuAccount.setTitle("Account")

        self.actionCreateNote = QAction()
        self.actionCreateNote.setObjectName("actionCreateNote")
        self.actionCreateNote.setText("Create note")

        self.actionSelectAllNotes = QAction()
        self.actionSelectAllNotes.setObjectName("actionSelectAllNotes")
        self.actionSelectAllNotes.setText("Select all notes")

        self.actionDelete = QAction()
        self.actionDelete.setObjectName("actionDelete")
        self.actionDelete.setText("Delete")

        self.actionClose = QAction()
        self.actionClose.setObjectName("actionClose")
        self.actionClose.setText("Close")

        self.actionChangeLogin = QAction()
        self.actionChangeLogin.setObjectName("actionChangeLogin")
        self.actionChangeLogin.setText("Change login")

        self.actionChangePassword = QAction()
        self.actionChangePassword.setObjectName("actionChangePassword")
        self.actionChangePassword.setText("Change password")

        self.actionChangeEmail = QAction()
        self.actionChangeEmail.setObjectName("actionChangeEmail")
        self.actionChangeEmail.setText("Change email")

        self.actionDeleteAccount = QAction()
        self.actionDeleteAccount.setObjectName("actionDeleteAccount")
        self.actionDeleteAccount.setText("Delete account")

        self.menuFile.addAction(self.actionCreateNote)
        self.menuFile.addAction(self.actionSelectAllNotes)
        self.menuFile.addAction(self.actionDelete)
        self.menuFile.addAction(self.actionClose)

        self.menuAccount.addAction(self.actionChangeLogin)
        self.menuAccount.addAction(self.actionChangePassword)
        self.menuAccount.addAction(self.actionChangeEmail)
        self.menuAccount.addSeparator()
        self.menuAccount.addAction(self.actionDeleteAccount)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAccount.menuAction())

        self.setMenuBar(self.menubar)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = UserNotesWindow()
    window.show()
    sys.exit(app.exec())
